### ISSUE TITLE
Handle errors better: restore always

### ISSUE THREAD

**Issue by blueyed** [guotsuan/awesome-revelation#11]
In case of errors (e.g. https://github.com/guotsuan/awesome-revelation/issues/4), awesome-revelation does not restore the clients when it aborts, which results in a messed up state.

I think this could be fixed by wrapping the functionality, e.g. by using `pcall` and call the restore function always.

**Comment by guotsuan** [comment]
Hi,

Thank you very much for suggestions. Indeed, current revelation is not error-friendly. When I go home, I will merge your request. Thanks a lot.

Cheers,

**Comment by blueyed** [comment]
And what do you think about this issue? (there is no PR for it)
Is using `pcall` an option?

**Comment by guotsuan** [comment]
I think pcall is definite a good start.

**Comment by guotsuan** [comment]
Pall has been introduced. Now the module sometime can recover from the errors, not always though.

**Comment by blueyed** [comment]
@guotsuan 
Where is it?

**Comment by guotsuan** [comment]
Sorry @blueyed. It is still in the develop branch. I have tested it for almost a week.
