### ISSUE TITLE
hintbox box not worked well with awesome-3.5.6

### ISSUE THREAD

**Issue by wxg4net** [guotsuan/awesome-revelation#12]
the postion if hintbox box ...
https://github.com/wxg4net/awesome-revelation/commit/02deef50577d7952bcd609656df9ce8efcf17f46

**Comment by blueyed** [comment]
Can you please elaborate what does not work and how it's improved with that commit?

**Comment by wxg4net** [comment]
fixed. https://github.com/wxg4net/awesome-revelation/commit/91b301d8705cc28ad12f28ae0b85e5cbd4fa5457

**Comment by blueyed** [comment]
This is related to https://github.com/awesomeWM/awesome/pull/153.
