### ISSUE TITLE
error: ./revelation/init.lua:31: module 'gears.timer' not found

### ISSUE THREAD

**Issue by elandx** [guotsuan/awesome-revelation#14]
Trying upgrade to the new version I got the error: ./revelation/init.lua:31: module 'gears.timer' not found .
I have awesome v3.5.6 (Lua 5.3) running on Arch Linux.

**Comment by guotsuan** [comment]
Hi,
This is because gears.timer is in develop/github version , not in released version 3.5.6. I have updated code and replaced the 'gears.timer' with other function that is available in version 3.5.6.

**Comment by elandx** [comment]
Hi, 
Thank You for explanations and fix. Those error gone, but new appears:
error while running function
stack traceback:
	./revelation/init.lua:68: in main chunk
	[C]: in function 'require'
	/home/elk/.config/awesome/rc.lua:22: in main chunk    
error: ./revelation/init.lua:68: attempt to index a nil value (field 'xresources')

('require' in line 22 is "local revelation=require("revelation")" )
Thanks

**Comment by guotsuan** [comment]
Hi,

Could you try to run the command 'locate beautiful/xresources.lua' to see if you have xresources.lua file in your system?

**Comment by elandx** [comment]
Hi,
No, file xresources.lua is absent ... I have only
/usr/share/awesome/lib/beautiful.lua

**Comment by guotsuan** [comment]
I see. It is the same reason. I had merge a pull request before, which I did not realise it is so heavily dependent on the version of awesome. Could you try the develop branch of awesome-revelation. I think that version should work with awesome 3.5.6 just fine. In functions, these two branches are almost same.

**Comment by elandx** [comment]
Hi,
it turns out that none of available revelations work with latest stable awesome.  Yours and https://github.com/bioe007/awesome-revelation -- not. I am quite satisfied with previous 2014 year version (fortunately backuped by me), but update breaks things ...
IMHO it would be better if you change awesome version in description from >=3.5 to development/unstable.
Thanks

**Comment by guotsuan** [comment]
Hi,
Thank you very much for the information. I have create another awesome-revelation package on AUR, which is only for awesome 3.5.6 stable version. I have checked myself with awesome 3.5.6. It works. 
You can use that package it you want. On github, I also create a stable branch, which host the codes corresponding to the that package. You are welcome to checkout them out and try.

**Comment by elandx** [comment]
Hi,
it turns out that none of available revelations work with latest stable awesome.  Yours and https://github.com/bioe007/awesome-revelation -- not. I am quite satisfied with previous 2014 year version (fortunately backuped by me), but update breaks things ...
IMHO it would be better if you change awesome version in description from >=3.5 to development/unstable.
Thanks

**Comment by elandx** [comment]
Hi,

I cloned the stable branch, it works as it should. Thank you for quick fix.

Best
