### ISSUE TITLE
Revelation not working with 3.5.6 and master branch

### ISSUE THREAD

**Issue by mikar** [guotsuan/awesome-revelation#22]
Hey, 

revelation is not working for me.
When calling revelation I get an error and nothing happens:

```lua
W: awesome: luaA_dofunction:78: error while running function
stack traceback:
	/home/max/.config/awesome/revelation/init.lua:230: in function 'revelation.restore'
	/home/max/.config/awesome/revelation/init.lua:193: in function 'revelation.expose'
	(...tail calls...)
	/usr/share/awesome/lib/awful/key.lua:42: in function </usr/share/awesome/lib/awful/key.lua:42>
error: /home/max/.config/awesome/revelation/init.lua:230: attempt to index a nil value (field '?')
```

**Comment by blueyed** [comment]
IIRC you are supposed to use the stable branch with stable awesome?!
https://github.com/guotsuan/awesome-revelation/tree/stable

**Comment by mikar** [comment]
3.5.6 is the stable version.

**Comment by guotsuan** [comment]
Hi @mikar,

Could you paste the output of comand 'awesome --version' here. So I can see which version of awesome you use. Thank you very much.

**Comment by mikar** [comment]
```
$ awesome --version
awesome v3.5.6 (For Those About To Rock)
 • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔
```

**Comment by guotsuan** [comment]
Hi @mikar,
Could you check if you add ```revelation.init()``` after ```beautiful.init()``` in your rc.lua?
Thanks.

**Comment by mikar** [comment]
No, i definitely didn't do that. Shame on me for not reading the README properly, sorry.
