### ISSUE TITLE
Running revelation.init() and beautiful.init("path")

### ISSUE THREAD

**Issue by Alex-Aralis** [guotsuan/awesome-revelation#25]
Init is never run in the source or specified to be run in the configuration portion of the readme.me for either beautiful or revelation.  

This version will crash without running init.  This I'm not sure how this extension would ever work without that step unless I'm missing something huge.

**Comment by guotsuan** [comment]
Which version of awesome you are using? 
What do you mean by the revelation.init() never run in the source? What errors do you get when you
put revelation.init() in your rc.lua?

**Comment by Alex-Aralis** [comment]
I'm using awesome 3.5.9

When I put revelation.init() in rc.lua and beautiful.init("theme path") in init.lua my problems are resolved.

**Comment by guotsuan** [comment]
Great
