### ISSUE TITLE
Fails to start on awesome 3.5.6

### ISSUE THREAD

**Issue by bijancn** [guotsuan/awesome-revelation#26]
When I put
```
local revelation = require("revelation")
local gears     = require("gears")
local awful     = require("awful")
awful.rules     = require("awful.rules")
                  require("awful.autofocus")
local wibox     = require("wibox")
local beautiful = require("beautiful")
local naughty   = require("naughty")
local drop      = require("scratchdrop")
local lain      = require("lain")
beautiful.init(os.getenv("HOME") .. "/.config/awesome/themes/powerarrow-darker/theme.lua")
revelation.init()
```
so the require at the top and revelation init after beautiful init, I get an error on this line (44 in init.lua):
```
if type(awful.client.object.toggle_tag) == 'function' then
```
(Can't access object it is Nil).
When I comment out the the `if` and the first branch it works.
Version is 3.5.6 and lua.rc is based on copycat powerarrow-darker.

**Comment by guotsuan** [comment]
I just tried to fix this problem. Could you checkout the new version and see if it works now on awesome 3.5.6?

**Comment by bijancn** [comment]
LGTM! No more error and still works beautifully. Thanks :)
