### ISSUE TITLE
unable to click on client in revelation

### ISSUE THREAD

**Issue by lanrat** [guotsuan/awesome-revelation#27]
When in the revelation view, clicking on a client/window does not take you to it's tag, instead it merely exits the revelation view.

**Comment by guotsuan** [comment]
Can you see any errors? It happens to any client or just some of clients?

**Comment by lanrat** [comment]
No errors appear to be thrown, and it happens on every client I have tested (chrome, terminal, file manager, etc...).
Using the hotkeys to jump to a client work just fine.

I'm using revelation with the default options.(https://github.com/lanrat/dotfiles/blob/master/awesome/rc.lua)

**Comment by guotsuan** [comment]
I will try to debug it tonight. by the way what version of awesome WM you are using now
?   You can get the version of awesome by command 'awesome --version'

Thanks.

**Comment by lanrat** [comment]
@guotsuan I'm running awesome v3.5.6.

I pulled your latest changes but didn't notice any change.

**Comment by lanrat** [comment]
Update: with the new changes clicking on the clients do nothing, in the old version clicking on a client closed revelation.

**Comment by guotsuan** [comment]
Sorry for the confusion. Could you checkout the new codes and try it again. The problem is caused by the codes try to maintain the backwards compatibility.

**Comment by lanrat** [comment]
Works now!

Thanks for the quick fix!
