### ISSUE TITLE
awesome-revelation isn't working with awesome upstream

### ISSUE THREAD

**Issue by aajjbb** [guotsuan/awesome-revelation#30]
Hi,

Revelation isn't working with upstream awesome. The error message is:

`Oops!, something is wrong in revelation.expose_callback! `
`.config/awesome/awesome-revelation/init.lua:250: attempt to index a nil value (field '?')`

I'm using `awesome v4.1-207-g24edeac4 (Technologic)` (upstream from git).
Revelation is also from git upstream.

**Comment by guotsuan** [comment]
Thanks for the feedback. I will look into it soon.

**Comment by taurgal** [comment]
You probably forgot to add "revelation.init()" to your rc.lua

**Comment by aajjbb** [comment]
I can't even believe I forgot it  :disappointed: . Thanks @taurgal
