### ISSUE TITLE
Error on awesome-3.5.3

### ISSUE THREAD

**Issue by Teknocrat** [guotsuan/awesome-revelation#4]
W: awesome: a_glib_poll:239: Last main loop iteration took 0.548 this warning to that value.
W: awesome: luaA_dofunction:78: error while running function
stack traceback:
        /home/foo/.config/awesome/revelation/init.lua:166: in function </home/foo/.config/awesome/revelation/init.lua:124>
        (tail call): ?
        /usr/share/awesome/lib/awful/key.lua:42: in function </usr/share/awesome/lib/awful/key.lua:42>
error: /home/foo/.config/awesome/revelation/init.lua:166: attempt to index field '?' (a nil value)

Any ideas?

**Comment by blueyed** [comment]
This happens with too many windows/clients.

I've just had the same, fix is provided in https://github.com/guotsuan/awesome-revelation/pull/8.
