### ISSUE TITLE
Windows not restored to original state after running revelation

### ISSUE THREAD

**Issue by taylor** [guotsuan/awesome-revelation#5]
After running revelation ( 2014-02-19) in Awesome v3.5.5 the windows are not restored to the original size and location.  The same issue happens when selecting a window and when pressing escape.

**Comment by blueyed** [comment]
Is this still an issue for you?

Do you see any error, which might cause this?

**Comment by taylor** [comment]
No errors.  Still an issue.  No change.

**Comment by blueyed** [comment]
You can add some print statements to see what is happening.

You are welcome to join #awesome on irc.oftc.net, if you need help.

**Comment by blueyed** [comment]
My guess still is that there's an error (in ~/.xsession-errors etc), which makes revelation abort.
