### ISSUE TITLE
bring all clients to current tag

### ISSUE THREAD

**Issue by r8b7xy** [guotsuan/awesome-revelation#6]
Is it possible to bring all clients to current tag? I've already disabled zoom option and I wonder whether it is possible to disable additional tag ('Revision') which is created every time.

**Comment by guotsuan** [comment]
I think it may be possible. I need to try it.  However what happen if you select one of you client you try to focus. Do you want to bring that client to current tag, or you want to jump to that tag and then focus on that client. If latter, what happen to the 'current' tag (before jumping), which already gather all of other clients.

Sorry, I 'm just no sure why you want disable additional tag ('Revision'). It is just a temporal tag, it will 
vanish  after you select a client.

**Comment by r8b7xy** [comment]
As i see it's far more complicated. I've asked this question because I was curious if 'awful.tag.history.restore' could work propely. Now when jumping from tag 'Revision' to the tag which have client I'd like to focus and then pressing mod+Esc keys history restore is trying to jump to the tag which doesn't exist anymore ('Revision').

**Comment by guotsuan** [comment]
Hi,
Thank you for the explanation. I'm now understand a bit more about your questions.

For example, let us assume, we have a terminal under tag A, and firefox under tag B.
Now we are focusing on the terminal. If I active 'revelation' by pressing mod + A, then we select and 
focus on firefox under tag B.  Then if you press mod + ESC, which is restore history.  you expect to jump back to terminal under Tag A, but not to jump to jump to tag 'revelation', which is not exist anymore?

**Comment by r8b7xy** [comment]
Yes, this is me exact expectation.

**Comment by r8b7xy** [comment]
Yes. This is what I exactly expect.

**Comment by guotsuan** [comment]
I see. What version of awesome are you using now. 
I tried this with my version of awesome, which is, 3.5.6. 
The behaviour of of 'revelation'  with my awesome is just as same as you expected...

**Comment by r8b7xy** [comment]
3.5.6
Ok, let me dig into my config. I'll let you know whether or not I find something.
If you have few moments this is [my config](https://github.com/r8b7xy/dotfiles/tree/master/awesome).

**Comment by r8b7xy** [comment]
Weird. After reboot everything works as you said. Even if earlier I had always been restarting awesome every time I had changed rc.
Thanks for your help and commitment. :)

**Comment by guotsuan** [comment]
You are very welcome. Hope you enjoy the awesome with revelation. Feel free to drop me a line about any questions or ideas about the revelation. Have a nice day.
