### ISSUE TITLE
Persistent "Revelation" tag

### ISSUE THREAD

**Issue by aajjbb** [guotsuan/awesome-revelation#7]
Hi, I just cloned the project and found it great.

The only thing that bothered me was the fact that after choosing a client, the just created "Revelation" tag persisted on my wibox, which is somehow 'pollutant'. So I adapted it to delete this tag after choosing the client.

It should be important to be added to the project ?

**Comment by guotsuan** [comment]
Hi, 

You are very welcome. 
I'm wondering which version of awesome you are using.  Usually the "Revelation" tag will disappear (be hidden) after you choose a client.  Or you could also generate the pull request I can also look at what is happening. 

Cheers,

**Comment by aajjbb** [comment]
I'm using awesome v3.5.6 with Lua 5.2, should it happen with this version ? If necessary, I can do pull request with this changes (just adding a tag removal on two pieces of coe)

Thank you,

**Comment by guotsuan** [comment]
No. it should not happen.  I think I use the same version. Could you do the pull request? I would like to try and find out what is the problem. Thank you very much.

**Comment by aajjbb** [comment]
Hi,
I'm sorry, it was a fault on my configurations, shame on me. I really liked the project, besides my fail, if I could help in something on the project, I'd appreciate to.

Thanks for your attention.

**Comment by guotsuan** [comment]
:D. No problem at all. You are very welcome to contribute to this project in any way you like. Feel free
to drop a line about any idea or suggestion about it.

**Comment by blueyed** [comment]
I'm also glad it worked out.. :)

This issue can be closed then.
